[package]
name = "autonomous_car"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
icp_2d = "0.1.2"
tokio-serial = "5.4.1"
sysinfo = "0.30.7"
tokio = { version = "1", features = ["full"] }
